name: BuildBattle
version: 0.1
description: Gestion des builbattle de BuildersCoffee.
author: Ketsu_sama
main: eu.builderscoffee.expresso.ExpressoBukkit
depend: [ API, Commons, PlotSquared ]
api-version: 1.18
commands:
  game:
    description: Gérer le build battle
  jury:
    description: Le menu jury
  group:
    description: Gestion de groupe
  eplot:
    description: Plot custom